#!/usr/bin/python3
import sys
import pickle
import subprocess 
from collections import Counter



def main():
    if len(sys.argv) < 2:
        with open("/tmp/selected.data", "rb") as f:
            selected = pickle.load(f) 
    else:
        target = sys.argv[1] 
        with open("/tmp/cap.data", "rb") as f:
            data = pickle.load(f) 
            selected = data[target]
    subprocess.run("pbcopy", universal_newlines=True, input=selected)

    print(selected)


if __name__ == "__main__":
    main()
